name: Update risk dataset (weekly)

on:
  schedule:
    - cron: "0 2 * * 6"     # Every Saturday at 02:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-risk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Yahoo Finance connection
        run: python src/test_yfinance.py

      - name: Run compute_risk.py
        run: python src/compute_risk.py

      - name: Commit CSV
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add risk_weekly_history.csv
          git commit -m "Update risk dataset" || echo "No changes to commit"
          git push