name: Update macro dataset

on:
  schedule:
    - cron: "0 3 * * 6"   # Sat 03:00 UTC (after your risk job)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-macro:
    runs-on: ubuntu-latest
    steps:
      - name: Kickoff marker
        run: echo "Runner started for update-macro ✅"

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      # If you add FRED_API_KEY in repo secrets, expose it here
      - name: Set FRED key (optional)
        if: ${{ secrets.FRED_API_KEY != '' }}
        run: echo "FRED_API_KEY=${{ secrets.FRED_API_KEY }}" >> $GITHUB_ENV

      # (Optional) quick connection check — won’t fail the run
      - name: Test FRED (non-blocking)
        continue-on-error: true
        run: python src/test_fred.py

      - name: Compute macro dataset
        run: python src/compute_macro.py

      - name: Commit macro_history.csv
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add macro_history.csv
          git commit -m "Update macro_history" || echo "No changes"
          git push