name: Weekly signals updater
on:
  schedule:
    - cron: "0 2 * * 6"   # SAT 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      # ✅ NEW: quick API smoke test
      - name: Test Yahoo Finance API
        run: python src/test_yfinance.py

      # Optional: list files to confirm paths
      - name: List repo files
        run: ls -R

      - name: Compute signals
        run: python src/compute_risk.py

      - name: Commit CSV
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add data/risk_weekly_history.csv
          git commit -m "Weekly update" || echo "No changes"
          git push